/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MarketingContent = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'tagline' : IDL.Text,
  'appName' : IDL.Text,
  'ctaText' : IDL.Text,
});

export const idlService = IDL.Service({
  'getMarketingContent' : IDL.Func([], [MarketingContent], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MarketingContent = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'tagline' : IDL.Text,
    'appName' : IDL.Text,
    'ctaText' : IDL.Text,
  });
  
  return IDL.Service({
    'getMarketingContent' : IDL.Func([], [MarketingContent], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };